### PR TITLE
WIP: Improve stack traces, lift requirement for custom debug_backtrace() mock

### PR DESCRIPTION
**Pull request by YuriyNasretdinov**
This pull request denotes only current work-in-progress. I did not perform large-scale tests that nothing is really broken so I suggest testing these changes on your repository first before accepting this pull request.

So, here is the description of what I changed:

1. Split classes to different files and require them explicitly to prevent autoload issues.
2. Change the way that functions are called: only internal functions are now wrapped in ::callFunction(...), but not the user-defined ones.
User-defined functions are now rewritten in a similar fashion as it is now done with user-defined methods.
This change allows to remove several extra lines in stack traces for each function call.
3. Change the way files are rewritten: temporarily redefine "file" URL stream before file include so that debuggers work without any proxies and stack traces already show original files.
4. Introduce the new class SoftMocksAccelerator that allows to do warmup using several processes. It is provided so that people do not need to write this code themselves each time they want something like this.
5. Because of (1-4), a lot of mocks for internal functions have been removed as they are no longer necessary in most cases.

### CODE REVIEW

**Comment by mougrim** [comment]
@YuriyNasretdinov, thanks for your contribution!
Tests failed [https://travis-ci.org/badoo/soft-mocks/builds/422157820](https://travis-ci.org/badoo/soft-mocks/builds/422157820).
Also new version of soft-mocks is prepared in v2 branch, your changes conflict with it.
@abrosimov is main maintainer of soft-mocks. I think better to discuss with him so big changes.
It's not simple to review, because changes moved to other files.

**Comment by YuriyNasretdinov** [comment]
I can see that tests fail but I do not see why. When I run tests on unpatched phpunit I get totally different results.

Changes moved to other files but I can merge them back together if it will simplify the review process. I did not change too much, actually :)

**Comment by mougrim** [comment]
> I can see that tests fail but I do not see why. When I run tests on unpatched phpunit I get totally different results.

Try to install and run tests in next way:
```bash
mkdir /tmp/mocks/
git clone git@github.com:YuriyNasretdinov/soft-mocks.git
cd soft-mocks
composer update --verbose // patches to phpunit should be applied during install
vendor/bin/phpunit // run tests
```

> Changes moved to other files but I can merge them back together if it will simplify the review process. I did not change too much, actually :)

I think better to separate divide soft-mocks to files and other changes to two pull requests for more simple review.
Please create PRs based on v2 branch.
Anyway about divide soft-mocks to files it would be great to do it carefully, and discuss with @abrosimov.

**Comment by Sannis** [comment]
Looks outdated and not so easy to merge.

**Comment by YuriyNasretdinov** [comment]
Not easy to merge: yes
Outdated: not at all! By using 'soft://' custom wrapper and returning the original filename in it it is possible to get rid of debug_backtrace() mock as well as allow debugging without any proxies and so much more!

**Pull request closed without merging**
